module.exports.privPem = `-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgGlndUv/Lgk6j/tNn38TkyksX1x/WBtfKpPfuobeeMfOhRANCAAQTs1fXwUkTZvGI12UPa+kvkibfpQHs5KTDb4arbDJJCZf0EtWhNdmT6Ieu/W8Yo4gUZRsKf0K+hZjjW8DeY5d5
-----END PRIVATE KEY-----`;

module.exports.pubPem = `-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE7NX18FJE2bxiNdlD2vpL5Im36UB7OSkw2+Gq2wySQmX9BLVoTXZk+iHrv1vGKOIFGUbCn9CvoWY41vA3mOXeQ==
-----END PUBLIC KEY-----`;
