module.exports.privPem = `-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgs6DWFZwZV9VHPP+RBbmp
rl6x32Z5TfN+EnwL/Sl+B/ChRANCAAQEkwvzRuRk4ylhedaYNZ8h+8wfkuV2E89a
0+GD0RaAMKkE3LJoPUnTihYLtqO6bgWufMCl0UelAAtyo9YW09O5
-----END PRIVATE KEY-----`;

module.exports.pubPem = `-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE7NX18FJE2bxiNdlD2vpL5Im36UB7OSkw2+Gq2wySQmX9BLVoTXZk+iHrv1vGKOIFGUbCn9CvoWY41vA3mOXeQ==
-----END PUBLIC KEY-----`;
